edb\_exception
==============

.. currentmodule:: pyedb.grpc.edb

.. automethod:: Edb.edb_exception